version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: concurrently
    versions:
    - 6.0.1
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.13
    - 7.13.14
    - 7.13.8
  - dependency-name: apollo-server-express
    versions:
    - 2.20.0
    - 2.21.0
    - 2.21.1
    - 2.21.2
    - 2.22.1
    - 2.22.2
  - dependency-name: "@babel/register"
    versions:
    - 7.12.13
    - 7.13.0
    - 7.13.14
  - dependency-name: "@babel/node"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.12
  - dependency-name: sequelize
    versions:
    - 6.6.1
  - dependency-name: apollo-server
    versions:
    - 2.19.2
    - 2.20.0
    - 2.21.0
    - 2.21.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: husky
    versions:
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
  - dependency-name: chai
    versions:
    - 4.3.0
    - 4.3.1
    - 4.3.3
  - dependency-name: mocha
    versions:
    - 8.3.0
