version: '3.5'

services:
  postgres:
    container_name: users-api-database
    image: postgres:11
    environment:
      POSTGRES_USER: boilerplate
      POSTGRES_PASSWORD: boilerplate
      POSTGRES_DB: users-api-database
      PGDATA: /data/postgres/user
    volumes:
      - postgres:/data/postgres/user
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:
